apiVersion: v1
data: 
  {{- range $key, $val := .Values.configmap.data }}
  {{ $key }}: {{ quote $val }}
  {{- end}}
  
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-conf
  namespace: {{ .Release.Namespace }}
